export const expandedQuestions = [
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "What is required to vote in a federal election?",
    options: ['Canadian citizenship and being at least 18', 'Owning property', 'Being a taxpayer', 'Holding a job'],
    correct: "Canadian citizenship and being at least 18",
    category: "Federal Elections",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "Who was the first Prime Minister of Canada?",
    options: ['Pierre Trudeau', 'John A. Macdonald', 'Wilfrid Laurier', 'Justin Trudeau'],
    correct: "John A. Macdonald",
    category: "History",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "What is the role of the Governor General?",
    options: ['Lead the military', 'Represent the monarch in Canada', 'Pass laws', 'Lead the opposition'],
    correct: "Represent the monarch in Canada",
    category: "Government",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "What is the largest province in Canada by area?",
    options: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    correct: "Quebec",
    category: "Geography",
  },
  {
    question: "What is the national animal of Canada?",
    options: ['Moose', 'Beaver', 'Polar Bear', 'Lynx'],
    correct: "Beaver",
    category: "Symbols",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
  {
    question: "Which of the following is a responsibility of Canadian citizens?",
    options: ['Owning property', 'Serving on a jury', 'Joining a political party', 'Learning a second language'],
    correct: "Serving on a jury",
    category: "Rights & Responsibilities",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "What is the significance of July 1st in Canada?",
    options: ['Remembrance Day', 'Canada Day', 'Victoria Day', 'Thanksgiving'],
    correct: "Canada Day",
    category: "Symbols",
  },
  {
    question: "What is Canada’s national currency?",
    options: ['Canadian Dollar', 'US Dollar', 'Euro', 'Pound Sterling'],
    correct: "Canadian Dollar",
    category: "Economy",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "Who is the Head of State in Canada?",
    options: ['Prime Minister', 'The Queen/King', 'Governor General', 'President'],
    correct: "The Queen/King",
    category: "Government",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "What is the longest river in Canada?",
    options: ['St. Lawrence River', 'Mackenzie River', 'Fraser River', 'Ottawa River'],
    correct: "Mackenzie River",
    category: "Geography",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "When did Canada become a country?",
    options: ['1776', '1867', '1914', '1982'],
    correct: "1867",
    category: "History",
  },
  {
    question: "What was the War of 1812 fought between?",
    options: ['Canada and the United States', 'Britain and France', 'Canada and France', 'Canada and Mexico'],
    correct: "Canada and the United States",
    category: "History",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "What are the fundamental freedoms protected by the Canadian Charter?",
    options: ['Freedom of speech, religion, and assembly', 'Right to bear arms', 'Right to privacy', 'Freedom from taxation'],
    correct: "Freedom of speech, religion, and assembly",
    category: "Rights & Responsibilities",
  },
  {
    question: "How often are federal elections held in Canada?",
    options: ['Every 4 years', 'Every 5 years', 'Every 6 years', 'Every 3 years'],
    correct: "Every 4 years",
    category: "Federal Elections",
  },
  {
    question: "Which industry is the largest contributor to Canada's economy?",
    options: ['Technology', 'Oil and Gas', 'Automotive', 'Agriculture'],
    correct: "Oil and Gas",
    category: "Economy",
  },
];